/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogo;

/**
 *
 * @author mateu
 */

import java.util.ArrayList;
import java.util.Arrays;

public class TelaDeRanking extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeRanking
     */
    public TelaDeRanking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloRanking = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        textoJogador4 = new javax.swing.JLabel();
        textoJogador3 = new javax.swing.JLabel();
        textoJogador2 = new javax.swing.JLabel();
        textoJogador1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textoJogador5 = new javax.swing.JLabel();
        tituloUsuario = new javax.swing.JLabel();
        tituloPontuacao = new javax.swing.JLabel();
        tituloTentativas = new javax.swing.JLabel();
        textoPontuacao1 = new javax.swing.JLabel();
        textoPontuacao2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoPontuacao3 = new javax.swing.JLabel();
        textoPontuacao4 = new javax.swing.JLabel();
        textoPontuacao5 = new javax.swing.JLabel();
        textoTentativas1 = new javax.swing.JLabel();
        textoTentativas2 = new javax.swing.JLabel();
        textoTentativas3 = new javax.swing.JLabel();
        textoTentativas4 = new javax.swing.JLabel();
        textoTentativas5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(1128, 720));

        tituloRanking.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        tituloRanking.setForeground(new java.awt.Color(255, 255, 255));
        tituloRanking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRanking.setText("RANKING");

        botaoVoltar.setBackground(new java.awt.Color(0, 0, 45));
        botaoVoltar.setIcon(new javax.swing.ImageIcon("D:\\Documentos\\Mauá\\Primeiro Semestre\\Projeto Integrador Interdisciplinar\\Codigos\\src\\main\\java\\com\\mycompany\\jogo\\bVoltar.png")); // NOI18N
        botaoVoltar.setBorder(null);
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        textoJogador4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoJogador4.setForeground(new java.awt.Color(255, 255, 255));
        textoJogador4.setText("a");

        textoJogador3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoJogador3.setForeground(new java.awt.Color(255, 255, 255));
        textoJogador3.setText("a");

        textoJogador2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoJogador2.setForeground(new java.awt.Color(255, 255, 255));
        textoJogador2.setText("a");

        textoJogador1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoJogador1.setForeground(new java.awt.Color(255, 255, 255));
        textoJogador1.setText("a");

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("1.");

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("2.");

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3.");

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("5.");

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("4.");

        textoJogador5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoJogador5.setForeground(new java.awt.Color(255, 255, 255));
        textoJogador5.setText("a");

        tituloUsuario.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        tituloUsuario.setForeground(new java.awt.Color(255, 255, 255));
        tituloUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloUsuario.setText("USUÁRIO");

        tituloPontuacao.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        tituloPontuacao.setForeground(new java.awt.Color(255, 255, 255));
        tituloPontuacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPontuacao.setText("PONTUAÇÃO");

        tituloTentativas.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        tituloTentativas.setForeground(new java.awt.Color(255, 255, 255));
        tituloTentativas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTentativas.setText("TENTATIVAS");

        textoPontuacao1.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textoPontuacao1.setForeground(new java.awt.Color(255, 255, 255));
        textoPontuacao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPontuacao1.setText("a");

        textoPontuacao2.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textoPontuacao2.setForeground(new java.awt.Color(255, 255, 255));
        textoPontuacao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPontuacao2.setText("a");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        textoPontuacao3.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textoPontuacao3.setForeground(new java.awt.Color(255, 255, 255));
        textoPontuacao3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPontuacao3.setText("a");

        textoPontuacao4.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textoPontuacao4.setForeground(new java.awt.Color(255, 255, 255));
        textoPontuacao4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPontuacao4.setText("a");

        textoPontuacao5.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textoPontuacao5.setForeground(new java.awt.Color(255, 255, 255));
        textoPontuacao5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPontuacao5.setText("a");

        textoTentativas1.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textoTentativas1.setForeground(new java.awt.Color(255, 255, 255));
        textoTentativas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTentativas1.setText("a");

        textoTentativas2.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textoTentativas2.setForeground(new java.awt.Color(255, 255, 255));
        textoTentativas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTentativas2.setText("a");

        textoTentativas3.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textoTentativas3.setForeground(new java.awt.Color(255, 255, 255));
        textoTentativas3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTentativas3.setText("a");

        textoTentativas4.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textoTentativas4.setForeground(new java.awt.Color(255, 255, 255));
        textoTentativas4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTentativas4.setText("a");

        textoTentativas5.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textoTentativas5.setForeground(new java.awt.Color(255, 255, 255));
        textoTentativas5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTentativas5.setText("a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(tituloRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(tituloUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textoJogador4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoJogador3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoJogador2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoJogador1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoJogador5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoPontuacao4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoPontuacao5, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(textoTentativas5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(textoTentativas4, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tituloPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textoPontuacao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoPontuacao3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textoPontuacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tituloTentativas, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(textoTentativas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoTentativas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoTentativas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tituloRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tituloPontuacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tituloTentativas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tituloUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoTentativas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoPontuacao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoPontuacao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoTentativas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoTentativas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoPontuacao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoJogador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textoJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoTentativas4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoPontuacao4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoJogador5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoPontuacao5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoTentativas5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(162, 162, 162))
        );

        try{
            RankingDAO dao = new RankingDAO();
            String jogador4 = dao.consultarRankingTop5Jogador4();
            int pontuacao4 = dao.consultarRankingTop5Pontuacao4();
            int tentativa4 = dao.consultarRankingTop5Tentativas4();
            textoJogador4.setText(jogador4);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            String jogador3 = dao.consultarRankingTop5Jogador3();
            int pontuacao3 = dao.consultarRankingTop5Pontuacao3();
            int tentativa3 = dao.consultarRankingTop5Tentativas3();
            textoJogador3.setText(jogador3);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            String jogador2 = dao.consultarRankingTop5Jogador2();
            int pontuacao2 = dao.consultarRankingTop5Pontuacao2();
            int tentativa2 = dao.consultarRankingTop5Tentativas2();
            textoJogador2.setText(jogador2);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            String jogador1 = dao.consultarRankingTop5Jogador1();

            int tentativa1 = dao.consultarRankingTop5Tentativas1();
            textoJogador1.setText(jogador1);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            String jogador5 = dao.consultarRankingTop5Jogador5();
            int pontuacao5 = dao.consultarRankingTop5Pontuacao5();
            int tentativa5 = dao.consultarRankingTop5Tentativas5();
            textoJogador5.setText(jogador5);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            int pontuacao1 = dao.consultarRankingTop5Pontuacao1();
            textoPontuacao1.setText(String.format("%d",pontuacao1));
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            int pontuacao2 = dao.consultarRankingTop5Pontuacao2();
            textoPontuacao2.setText(String.format("%d",pontuacao2));
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            int pontuacao3 = dao.consultarRankingTop5Pontuacao3();
            textoPontuacao3.setText(String.format("%d",pontuacao3));
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            int pontuacao4 = dao.consultarRankingTop5Pontuacao4();
            textoPontuacao4.setText(String.format("%d",pontuacao4));
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            int pontuacao5 = dao.consultarRankingTop5Pontuacao5();
            textoPontuacao5.setText(String.format("%d",pontuacao5));
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            int tentativas1 = dao.consultarRankingTop5Tentativas1();
            textoTentativas1.setText(String.format("%d",tentativas1));
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            int tentativas2 = dao.consultarRankingTop5Tentativas2();
            textoTentativas2.setText(String.format("%d",tentativas2));
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            int tentativas3 = dao.consultarRankingTop5Tentativas3();
            textoTentativas3.setText(String.format("%d",tentativas3));
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            int tentativas4 = dao.consultarRankingTop5Tentativas4();
            textoTentativas4.setText(String.format("%d",tentativas4));
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            RankingDAO dao = new RankingDAO();
            int tentativas5 = dao.consultarRankingTop5Tentativas5();
            textoTentativas5.setText(String.format("%d",tentativas5));
        }
        catch(Exception e){
            e.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeRanking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoJogador1;
    private javax.swing.JLabel textoJogador2;
    private javax.swing.JLabel textoJogador3;
    private javax.swing.JLabel textoJogador4;
    private javax.swing.JLabel textoJogador5;
    private javax.swing.JLabel textoPontuacao1;
    private javax.swing.JLabel textoPontuacao2;
    private javax.swing.JLabel textoPontuacao3;
    private javax.swing.JLabel textoPontuacao4;
    private javax.swing.JLabel textoPontuacao5;
    private javax.swing.JLabel textoTentativas1;
    private javax.swing.JLabel textoTentativas2;
    private javax.swing.JLabel textoTentativas3;
    private javax.swing.JLabel textoTentativas4;
    private javax.swing.JLabel textoTentativas5;
    private javax.swing.JLabel tituloPontuacao;
    private javax.swing.JLabel tituloRanking;
    private javax.swing.JLabel tituloTentativas;
    private javax.swing.JLabel tituloUsuario;
    // End of variables declaration//GEN-END:variables
}
