/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogo;

/**
 *
 * @author mateu
 */
public class TelaDeRegras extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeRegras
     */
    public TelaDeRegras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTelaDeRegras = new javax.swing.JPanel();
        tituloTelaDeRegras = new javax.swing.JLabel();
        textoRegra1 = new javax.swing.JLabel();
        textoRegra2 = new javax.swing.JLabel();
        textoRegra3 = new javax.swing.JLabel();
        textoRegra4 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelTelaDeRegras.setBackground(new java.awt.Color(0, 0, 45));
        painelTelaDeRegras.setForeground(new java.awt.Color(0, 0, 45));

        tituloTelaDeRegras.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        tituloTelaDeRegras.setForeground(new java.awt.Color(187, 187, 187));
        tituloTelaDeRegras.setText("Regras");

        textoRegra1.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        textoRegra1.setForeground(new java.awt.Color(187, 187, 187));
        textoRegra1.setText("1.  Cada fase é composta por três questões ");

        textoRegra2.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        textoRegra2.setForeground(new java.awt.Color(187, 187, 187));
        textoRegra2.setText("2. Cada questão contém apenas uma resposta correta ");

        textoRegra3.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        textoRegra3.setForeground(new java.awt.Color(187, 187, 187));
        textoRegra3.setText("3. Fases mais avançadas podem conter conceitos de outras fases anteriores ");

        textoRegra4.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        textoRegra4.setForeground(new java.awt.Color(187, 187, 187));
        textoRegra4.setText("4. Divirta-se!");

        botaoVoltar.setBackground(new java.awt.Color(0, 0, 45));
        botaoVoltar.setIcon(new javax.swing.ImageIcon("D:\\Documentos\\Mauá\\Primeiro Semestre\\Projeto Integrador Interdisciplinar\\Codigos\\src\\main\\java\\com\\mycompany\\jogo\\bVoltar.png")); // NOI18N
        botaoVoltar.setText("botaoVoltar");
        botaoVoltar.setBorder(null);
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTelaDeRegrasLayout = new javax.swing.GroupLayout(painelTelaDeRegras);
        painelTelaDeRegras.setLayout(painelTelaDeRegrasLayout);
        painelTelaDeRegrasLayout.setHorizontalGroup(
            painelTelaDeRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaDeRegrasLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(painelTelaDeRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTelaDeRegrasLayout.createSequentialGroup()
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(373, 373, 373)
                        .addComponent(tituloTelaDeRegras))
                    .addGroup(painelTelaDeRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textoRegra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoRegra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoRegra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoRegra4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        painelTelaDeRegrasLayout.setVerticalGroup(
            painelTelaDeRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaDeRegrasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(painelTelaDeRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloTelaDeRegras)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(textoRegra1)
                .addGap(34, 34, 34)
                .addComponent(textoRegra2)
                .addGap(34, 34, 34)
                .addComponent(textoRegra3)
                .addGap(34, 34, 34)
                .addComponent(textoRegra4)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTelaDeRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTelaDeRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeRegras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeRegras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeRegras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeRegras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeRegras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPanel painelTelaDeRegras;
    private javax.swing.JLabel textoRegra1;
    private javax.swing.JLabel textoRegra2;
    private javax.swing.JLabel textoRegra3;
    private javax.swing.JLabel textoRegra4;
    private javax.swing.JLabel tituloTelaDeRegras;
    // End of variables declaration//GEN-END:variables
}
