/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogo;

/**
 *
 * @author Othavio
 */

import java.io.*;
import java.util.*; 
import org.apache.commons.io.FileUtils;
import javax.swing.*;
import java.io.File;


public class TelaMaterialIfElifElse extends javax.swing.JFrame {

    /**
     * Creates new form TelaMaterialIfElifElse
     */
    public TelaMaterialIfElifElse() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMaterialIfElifElse = new javax.swing.JPanel();
        ifElifElseLabel = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        botaoJogar = new javax.swing.JButton();
        materialIfElifElse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelMaterialIfElifElse.setBackground(new java.awt.Color(0, 0, 45));
        painelMaterialIfElifElse.setPreferredSize(new java.awt.Dimension(1128, 720));

        ifElifElseLabel.setBackground(new java.awt.Color(0, 0, 45));
        ifElifElseLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ifElifElseLabel.setForeground(new java.awt.Color(187, 187, 187));
        ifElifElseLabel.setText("If/Elif/Else");

        botaoVoltar.setBackground(new java.awt.Color(0, 0, 45));
        botaoVoltar.setForeground(new java.awt.Color(0, 0, 45));
        botaoVoltar.setIcon(new javax.swing.ImageIcon("D:\\Documentos\\Mauá\\Primeiro Semestre\\Projeto Integrador Interdisciplinar\\Codigos\\src\\main\\java\\com\\mycompany\\jogo\\bVoltar.png")); // NOI18N
        botaoVoltar.setText("jButton1");
        botaoVoltar.setBorder(null);
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoJogar.setBackground(new java.awt.Color(0, 0, 45));
        botaoJogar.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        botaoJogar.setForeground(new java.awt.Color(255, 255, 255));
        botaoJogar.setText("JOGAR");
        botaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogarActionPerformed(evt);
            }
        });

        materialIfElifElse.setText("jLabel1");

        javax.swing.GroupLayout painelMaterialIfElifElseLayout = new javax.swing.GroupLayout(painelMaterialIfElifElse);
        painelMaterialIfElifElse.setLayout(painelMaterialIfElifElseLayout);
        painelMaterialIfElifElseLayout.setHorizontalGroup(
            painelMaterialIfElifElseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMaterialIfElifElseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(painelMaterialIfElifElseLayout.createSequentialGroup()
                .addGroup(painelMaterialIfElifElseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMaterialIfElifElseLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(335, 335, 335)
                        .addComponent(ifElifElseLabel))
                    .addGroup(painelMaterialIfElifElseLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(materialIfElifElse, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        painelMaterialIfElifElseLayout.setVerticalGroup(
            painelMaterialIfElifElseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMaterialIfElifElseLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelMaterialIfElifElseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ifElifElseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(materialIfElifElse, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(botaoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        try{
            if (new MaterialDeApoioDAO().consultar_material_jogador(Jogador.nomeDoUsuario,2) == false)
            new MaterialDeApoioDAO().cadastrar_material_jogador(Jogador.nomeDoUsuario,2);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        MaterialDeApoioDAO dao = new MaterialDeApoioDAO();

        String material = dao.material(2);
        byte[] fotoMaterial = Base64.getDecoder().decode(material);
        Icon iconMaterial = new ImageIcon(fotoMaterial);
        materialIfElifElse.setIcon(iconMaterial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelMaterialIfElifElse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelMaterialIfElifElse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        new TelaMaterialDeApoio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogarActionPerformed
        new TelaDeFase2Nivel1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMaterialIfElifElse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMaterialIfElifElse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMaterialIfElifElse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMaterialIfElifElse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMaterialIfElifElse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoJogar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel ifElifElseLabel;
    private javax.swing.JLabel materialIfElifElse;
    private javax.swing.JPanel painelMaterialIfElifElse;
    // End of variables declaration//GEN-END:variables
}
