/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogo;

/**
 *
 * @author Othavio
 */

import java.io.*;
import java.util.*; 
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import org.apache.commons.io.FileUtils;
import javax.swing.*;

public class TelaDeFase6Nivel2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeFase6Nivel2
     */
    public TelaDeFase6Nivel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTelaFase6Nivel2 = new javax.swing.JPanel();
        perguntaFase6Nivel2 = new javax.swing.JLabel();
        primeiraResposta = new javax.swing.JButton();
        segundaResposta = new javax.swing.JButton();
        terceiraResposta = new javax.swing.JButton();
        quartaResposta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelTelaFase6Nivel2.setBackground(new java.awt.Color(0, 0, 45));

        perguntaFase6Nivel2.setBackground(new java.awt.Color(0, 0, 45));
        perguntaFase6Nivel2.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        perguntaFase6Nivel2.setForeground(new java.awt.Color(255, 255, 255));
        perguntaFase6Nivel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        primeiraResposta.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        primeiraResposta.setForeground(new java.awt.Color(255, 255, 255));
        primeiraResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiraRespostaActionPerformed(evt);
            }
        });

        segundaResposta.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        segundaResposta.setForeground(new java.awt.Color(255, 255, 255));
        segundaResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundaRespostaActionPerformed(evt);
            }
        });

        terceiraResposta.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        terceiraResposta.setForeground(new java.awt.Color(255, 255, 255));
        terceiraResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terceiraRespostaActionPerformed(evt);
            }
        });

        quartaResposta.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        quartaResposta.setForeground(new java.awt.Color(255, 255, 255));
        quartaResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quartaRespostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTelaFase6Nivel2Layout = new javax.swing.GroupLayout(painelTelaFase6Nivel2);
        painelTelaFase6Nivel2.setLayout(painelTelaFase6Nivel2Layout);
        painelTelaFase6Nivel2Layout.setHorizontalGroup(
            painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaFase6Nivel2Layout.createSequentialGroup()
                .addGroup(painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTelaFase6Nivel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(painelTelaFase6Nivel2Layout.createSequentialGroup()
                                .addComponent(terceiraResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quartaResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelTelaFase6Nivel2Layout.createSequentialGroup()
                                .addComponent(primeiraResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182)
                                .addComponent(segundaResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelTelaFase6Nivel2Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(perguntaFase6Nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        painelTelaFase6Nivel2Layout.setVerticalGroup(
            painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaFase6Nivel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(perguntaFase6Nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(segundaResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primeiraResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(terceiraResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quartaResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        Fases numero = new Fases(17);
        FasesDAO dao = new FasesDAO();
        String questao = dao.questao(numero);
        byte[] fotoQuestao = Base64.getDecoder().decode(questao);
        Icon iconQuestao = new ImageIcon(fotoQuestao);
        perguntaFase6Nivel2.setIcon(iconQuestao);
        String alternativa1 = dao.alternativa1(numero);
        byte[] fotoAlternativa1 = Base64.getDecoder().decode(alternativa1);
        Icon iconAlternativa1 = new ImageIcon(fotoAlternativa1);
        primeiraResposta.setIcon(iconAlternativa1);
        String alternativa2 = dao.alternativa2(numero);
        byte[] fotoAlternativa2 = Base64.getDecoder().decode(alternativa2);
        Icon iconAlternativa2 = new ImageIcon(fotoAlternativa2);
        segundaResposta.setIcon(iconAlternativa2);
        String alternativa3 = dao.alternativa3(numero);
        byte[] fotoAlternativa3 = Base64.getDecoder().decode(alternativa3);
        Icon iconAlternativa3 = new ImageIcon(fotoAlternativa3);
        terceiraResposta.setIcon(iconAlternativa3);
        String alternativa4 = dao.alternativa4(numero);
        byte[] fotoAlternativa4 = Base64.getDecoder().decode(alternativa4);
        Icon iconAlternativa4 = new ImageIcon(fotoAlternativa4);
        quartaResposta.setIcon(iconAlternativa4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTelaFase6Nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTelaFase6Nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primeiraRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiraRespostaActionPerformed
        try{
            String soundName = Ranking.audioErrado;    
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
            new TelaDeFase6Nivel3().setVisible(true);
            this.dispose();
        }
        catch(Exception e){
            e.printStackTrace();
        }    }//GEN-LAST:event_primeiraRespostaActionPerformed

    private void segundaRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundaRespostaActionPerformed
        try{
            String soundName = Ranking.audioErrado;    
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
            new TelaDeFase6Nivel3().setVisible(true);
            this.dispose();
        }
        catch(Exception e){
            e.printStackTrace();
        }    }//GEN-LAST:event_segundaRespostaActionPerformed

    private void quartaRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quartaRespostaActionPerformed
        try{
            String soundName = Ranking.audioErrado;    
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
            new TelaDeFase6Nivel3().setVisible(true);
            this.dispose();
        }
        catch(Exception e){
            e.printStackTrace();
        }    }//GEN-LAST:event_quartaRespostaActionPerformed

    private void terceiraRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terceiraRespostaActionPerformed
        try {
            String soundName = Ranking.audioCorreto;
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
            FasesDAO fases = new FasesDAO();
            if (fases.verificar_jogador_pergunta(17, Jogador.nomeDoUsuario) == false) {
                fases.enviar_jogador_pergunta(17, Jogador.nomeDoUsuario);
                Ranking.pontuacao += 100;
                Ranking ranking = new Ranking(Jogador.nomeDoUsuario);
                JogadorDAO dao = new JogadorDAO();
                RankingDAO dao2 = new RankingDAO();
                dao.atualizarPontuacao(Jogador.nomeDoUsuario, Ranking.pontuacao);
                dao2.atualizarPontuacao(Ranking.pontuacao, Jogador.nomeDoUsuario);
            }
            new TelaDeFase6Nivel3().setVisible(true);
            this.dispose();
        
    }
    catch(Exception e){
        e.printStackTrace();
    }    }//GEN-LAST:event_terceiraRespostaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase6Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase6Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase6Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase6Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeFase6Nivel2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelTelaFase6Nivel2;
    private javax.swing.JLabel perguntaFase6Nivel2;
    private javax.swing.JButton primeiraResposta;
    private javax.swing.JButton quartaResposta;
    private javax.swing.JButton segundaResposta;
    private javax.swing.JButton terceiraResposta;
    // End of variables declaration//GEN-END:variables
}
