/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogo;

import javax.swing.JOptionPane;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author mateu
 */
public class TelaDeCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCadastro
     */
    public TelaDeCadastro() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTelaDeCadastro = new javax.swing.JPanel();
        textoSenha = new javax.swing.JPasswordField();
        textoNome = new javax.swing.JTextField();
        textoEmail = new javax.swing.JTextField();
        textoIdade = new javax.swing.JTextField();
        textoTelefone = new javax.swing.JTextField();
        fotoNome = new javax.swing.JLabel();
        fotoEmail = new javax.swing.JLabel();
        fotoIdade = new javax.swing.JLabel();
        fotoCelular = new javax.swing.JLabel();
        fotoUsuario = new javax.swing.JLabel();
        fotoSenha = new javax.swing.JLabel();
        botaoEntrar = new javax.swing.JButton();
        descricaoNome = new javax.swing.JLabel();
        descricaoTelefone = new javax.swing.JLabel();
        descricaoUsuario = new javax.swing.JLabel();
        descricaoSenha = new javax.swing.JLabel();
        tituloPaginaCadastro = new javax.swing.JLabel();
        tituloCadastro = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelTelaDeCadastro.setBackground(new java.awt.Color(0, 0, 45));
        painelTelaDeCadastro.setToolTipText("");

        textoSenha.setBackground(new java.awt.Color(0, 0, 45));
        textoSenha.setForeground(new java.awt.Color(187, 187, 187));
        textoSenha.setText("senha");
        textoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoSenhaFocusLost(evt);
            }
        });
        textoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSenhaActionPerformed(evt);
            }
        });

        textoNome.setBackground(new java.awt.Color(0, 0, 45));
        textoNome.setForeground(new java.awt.Color(187, 187, 187));
        textoNome.setText("nome");
        textoNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoNomeFocusLost(evt);
            }
        });

        textoEmail.setBackground(new java.awt.Color(0, 0, 45));
        textoEmail.setForeground(new java.awt.Color(187, 187, 187));
        textoEmail.setText("email");
        textoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoEmailFocusLost(evt);
            }
        });

        textoIdade.setBackground(new java.awt.Color(0, 0, 45));
        textoIdade.setForeground(new java.awt.Color(187, 187, 187));
        textoIdade.setText("idade");
        textoIdade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoIdadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoIdadeFocusLost(evt);
            }
        });

        textoTelefone.setBackground(new java.awt.Color(0, 0, 45));
        textoTelefone.setForeground(new java.awt.Color(187, 187, 187));
        textoTelefone.setText("telefone");
        textoTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoTelefoneFocusLost(evt);
            }
        });
        textoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTelefoneActionPerformed(evt);
            }
        });

        fotoNome.setText("jLabel1");
        fotoNome.setToolTipText("");

        fotoEmail.setText("jLabel2");
        fotoEmail.setToolTipText("");

        fotoIdade.setText("jLabel3");
        fotoIdade.setToolTipText("");

        fotoCelular.setText("jLabel4");
        fotoCelular.setToolTipText("");

        fotoUsuario.setText("jLabel5");
        fotoUsuario.setToolTipText("");

        fotoSenha.setText("jLabel6");
        fotoSenha.setToolTipText("");

        botaoEntrar.setBackground(new java.awt.Color(0, 0, 45));
        botaoEntrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoEntrar.setForeground(new java.awt.Color(187, 187, 187));
        botaoEntrar.setText("Sign Up");
        botaoEntrar.setToolTipText("");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });

        descricaoNome.setBackground(new java.awt.Color(0, 0, 45));
        descricaoNome.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        descricaoNome.setForeground(new java.awt.Color(187, 187, 187));
        descricaoNome.setText("Nome Completo");

        descricaoTelefone.setBackground(new java.awt.Color(0, 0, 45));
        descricaoTelefone.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        descricaoTelefone.setForeground(new java.awt.Color(187, 187, 187));
        descricaoTelefone.setText("DDD + 9 digitos");

        descricaoUsuario.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        descricaoUsuario.setForeground(new java.awt.Color(187, 187, 187));
        descricaoUsuario.setText("Min - 4 Caracteres");

        descricaoSenha.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        descricaoSenha.setForeground(new java.awt.Color(187, 187, 187));
        descricaoSenha.setText("Min - 8 , Max - 20,1 Letra Maiuscula, 1 Número, 1 Caracter Especial");

        tituloPaginaCadastro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloPaginaCadastro.setForeground(new java.awt.Color(187, 187, 187));
        tituloPaginaCadastro.setText("ACADEMIA MAUÁ DE PROGRAMAÇÃO");

        tituloCadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloCadastro.setForeground(new java.awt.Color(187, 187, 187));
        tituloCadastro.setText("Cadastro");

        textoUsuario.setBackground(new java.awt.Color(0, 0, 45));
        textoUsuario.setForeground(new java.awt.Color(187, 187, 187));
        textoUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textoUsuario.setText("username");
        textoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoUsuarioFocusGained(evt);
            }
        });

        javax.swing.GroupLayout painelTelaDeCadastroLayout = new javax.swing.GroupLayout(painelTelaDeCadastro);
        painelTelaDeCadastro.setLayout(painelTelaDeCadastroLayout);
        painelTelaDeCadastroLayout.setHorizontalGroup(
            painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaDeCadastroLayout.createSequentialGroup()
                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTelaDeCadastroLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tituloPaginaCadastro))
                    .addGroup(painelTelaDeCadastroLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTelaDeCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTelaDeCadastroLayout.createSequentialGroup()
                        .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTelaDeCadastroLayout.createSequentialGroup()
                                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fotoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fotoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(descricaoUsuario)
                                    .addComponent(textoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(textoUsuario)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTelaDeCadastroLayout.createSequentialGroup()
                                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(painelTelaDeCadastroLayout.createSequentialGroup()
                                        .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fotoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fotoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fotoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10))
                                    .addGroup(painelTelaDeCadastroLayout.createSequentialGroup()
                                        .addComponent(fotoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descricaoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textoEmail)
                                        .addComponent(textoNome)
                                        .addComponent(textoIdade)
                                        .addComponent(textoTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                                    .addComponent(descricaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTelaDeCadastroLayout.createSequentialGroup()
                        .addComponent(tituloCadastro)
                        .addGap(295, 295, 295))))
        );
        painelTelaDeCadastroLayout.setVerticalGroup(
            painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaDeCadastroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tituloPaginaCadastro)
                .addGap(43, 43, 43)
                .addComponent(tituloCadastro)
                .addGap(51, 51, 51)
                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(descricaoNome)
                .addGap(18, 18, 18)
                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoEmail))
                .addGap(35, 35, 35)
                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoIdade))
                .addGap(35, 35, 35)
                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoCelular))
                .addGap(1, 1, 1)
                .addComponent(descricaoTelefone)
                .addGap(18, 18, 18)
                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fotoUsuario)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaoUsuario)
                .addGap(18, 18, 18)
                .addGroup(painelTelaDeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoSenha))
                .addGap(18, 18, 18)
                .addComponent(descricaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(botaoEntrar)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTelaDeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTelaDeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        painelTelaDeCadastro.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTelefoneActionPerformed

    private void textoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoSenhaActionPerformed

    private void textoNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoNomeFocusGained
        textoNome.setText("");
    }//GEN-LAST:event_textoNomeFocusGained

    private void textoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoEmailFocusGained
        textoEmail.setText("");
    }//GEN-LAST:event_textoEmailFocusGained

    private void textoIdadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoIdadeFocusGained
        textoIdade.setText("");
    }//GEN-LAST:event_textoIdadeFocusGained

    private void textoTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoTelefoneFocusGained
        textoTelefone.setText("");
    }//GEN-LAST:event_textoTelefoneFocusGained

    private void textoSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoSenhaFocusGained
        textoSenha.setText("");
    }//GEN-LAST:event_textoSenhaFocusGained

    private void textoNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoNomeFocusLost

    }//GEN-LAST:event_textoNomeFocusLost

    private void textoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoEmailFocusLost

    }//GEN-LAST:event_textoEmailFocusLost

    private void textoIdadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoIdadeFocusLost

    }//GEN-LAST:event_textoIdadeFocusLost

    private void textoTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoTelefoneFocusLost

    }//GEN-LAST:event_textoTelefoneFocusLost

    private void textoSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoSenhaFocusLost

    }//GEN-LAST:event_textoSenhaFocusLost

    private void textoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoUsuarioFocusGained
        textoUsuario.setText("");
    }//GEN-LAST:event_textoUsuarioFocusGained

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed

        try {
            String stringTextoNome = textoNome.getText();
            String stringTextoEmail = textoEmail.getText();
            String stringTextoIdade = textoIdade.getText();
            String stringTextoTelefone = textoTelefone.getText();
            String stringTextoUsuario = textoUsuario.getText();
            String stringTextoSenha = new String(textoSenha.getPassword());
            int intTextoIdade = 1;
            int soma = 0;
            try {
                intTextoIdade = Integer.parseInt(stringTextoIdade);
            } catch (Exception e) {
                soma = 1;
            }
            JogadorDAO dao = new JogadorDAO();
            RankingDAO dao2 = new RankingDAO();
            Jogador jogador2 = new Jogador(stringTextoUsuario, stringTextoSenha);

            char[] senhaChar = stringTextoSenha.toCharArray();
            char[] usuarioChar = stringTextoUsuario.toCharArray();
            char[] telefoneChar = stringTextoTelefone.toCharArray();

            boolean eNumero = false;
            for (char c : senhaChar) {
                if (Character.isDigit(c)) {
                    eNumero = true;
                }
            }
            boolean eCaracterEspecial = false;
            String specialCharactersString2 = "!@#$%&*()'+,-./:;<=>?[]^`{|}_";
            String underscore = "_";
            for (char c : senhaChar) {
                if (specialCharactersString2.contains(Character.toString(c))) {
                    eCaracterEspecial = true;
                }
            }
            boolean eCaracterEspecial2 = false;
            for (char c : usuarioChar) {
                if (underscore.contains(Character.toString(c))) {
                    eCaracterEspecial2 = true;
                }
            }

            boolean eNumero2 = true;
            for (char c : telefoneChar) {
                if (Character.isDigit(c) == false) {
                    eNumero2 = false;
                }
            }
            if (dao.verificar(jogador2)) {
                JOptionPane.showMessageDialog(null, "Esse usuário já existe!");
            } else {
                if (stringTextoEmail.contains("@")) {
                    int posicao_arroba = stringTextoEmail.indexOf("@");
                    if (stringTextoEmail.length() < 3) {
                        JOptionPane.showMessageDialog(null, "O email inserido não é válido!");
                        soma = 2;
                    }
                } else{
                    JOptionPane.showMessageDialog(null, "O email inserido não é válido!");
                    soma = 2;
                }
            }
            if (stringTextoTelefone.length() != 11 || eNumero2 == false) {
                JOptionPane.showMessageDialog(null, "O telefone inserido não é válido!");
            } else if (stringTextoUsuario.length() < 4 || eCaracterEspecial2 == false) {
                JOptionPane.showMessageDialog(null, "O username inserido não é válido!");
            } else if (stringTextoSenha.length() < 8 && stringTextoSenha.length() > 20 || eNumero == false || eCaracterEspecial == false) {
                JOptionPane.showMessageDialog(null, "A senha inserida não é válida!");
            } else if (soma == 1) {
                JOptionPane.showMessageDialog(null, "A idade inserida não é válida!");

            } else if (soma != 2) {
                Ranking ranking = new Ranking(stringTextoUsuario);

                Jogador jogador = new Jogador(stringTextoNome, stringTextoEmail, intTextoIdade, stringTextoTelefone, stringTextoUsuario, stringTextoSenha);
                dao.criar(jogador);
                dao.registrar(stringTextoUsuario, stringTextoSenha);
                dao.pegarPontuacao(stringTextoUsuario);
                dao2.criar(ranking);
                new TelaInicial().setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_botaoEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JLabel descricaoNome;
    private javax.swing.JLabel descricaoSenha;
    private javax.swing.JLabel descricaoTelefone;
    private javax.swing.JLabel descricaoUsuario;
    private javax.swing.JLabel fotoCelular;
    private javax.swing.JLabel fotoEmail;
    private javax.swing.JLabel fotoIdade;
    private javax.swing.JLabel fotoNome;
    private javax.swing.JLabel fotoSenha;
    private javax.swing.JLabel fotoUsuario;
    private javax.swing.JPanel painelTelaDeCadastro;
    private static javax.swing.JTextField textoEmail;
    private static javax.swing.JTextField textoIdade;
    private static javax.swing.JTextField textoNome;
    private static javax.swing.JPasswordField textoSenha;
    private static javax.swing.JTextField textoTelefone;
    private static javax.swing.JTextField textoUsuario;
    private javax.swing.JLabel tituloCadastro;
    private javax.swing.JLabel tituloPaginaCadastro;
    // End of variables declaration//GEN-END:variables
}
